site_name: PUMA
theme:
  name: material
  palette:
    primary: black
  font:
    text: Rubik
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  language: pt
repo_url: https://github.com/fga-eps-mds/2023-1-PUMA-Doc
markdown_extensions:
    - attr_list